"""update question model

Revision ID: fb0030d85dc5
Revises: c827f1e109c6
Create Date: 2025-08-13 09:47:56.361377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0030d85dc5'
down_revision: Union[str, Sequence[str], None] = 'c827f1e109c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_option_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'correct_option_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_option_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'correct_option_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
